<a href="https://colab.research.google.com/github/GuilhermeFMedici/Exercicios_em_Python/blob/main/Filtrando_Modificando_Adicionando_valores_do_df.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Adicionando Colunas, Modificando Colunas e Valores

### Vamos pegar o nosso dataframe novamente

In [ ]:
from google.colab import drive 
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import pandas as pd
#importando os arquivos
vendas_df = pd.read_csv(r'/content/drive/ My Drive/Analise de dados/Contoso - Vendas  - 2017.csv', sep=';')
produtos_df = pd.read_csv(r'/content/drive/ My Drive/Analise de dados/Contoso - Cadastro Produtos.csv', sep=';')
lojas_df = pd.read_csv(r'/content/drive/ My Drive/Analise de dados/Contoso - Lojas.csv', sep=';')
clientes_df = pd.read_csv(r'/content/drive/ My Drive/Analise de dados/Contoso - Clientes.csv', sep=';')

#Pegando apenas as colunas que queremos
clientes_df = clientes_df[['ID Cliente', 'E-mail']]
produtos_df = produtos_df[['ID Produto', 'Nome do Produto']]
lojas_df = lojas_df[['ID Loja', 'Nome da Loja']]

#mesclando e renomeando os dataframes
vendas_df = vendas_df.merge(produtos_df, on='ID Produto')
vendas_df = vendas_df.merge(lojas_df, on='ID Loja')
vendas_df = vendas_df.merge(clientes_df, on='ID Cliente').rename(columns={'E-mail': 'E-mail do Cliente'})
display(vendas_df)
vendas_df.info()

        Numero da Venda  ...            E-mail do Cliente
0                     1  ...       rbrumfieldmy@ameblo.jp
1                880458  ...       rbrumfieldmy@ameblo.jp
2                191019  ...       rbrumfieldmy@ameblo.jp
3                 18610  ...       rbrumfieldmy@ameblo.jp
4                287704  ...       rbrumfieldmy@ameblo.jp
...                 ...  ...                          ...
980637           878244  ...           edowner9m@imdb.com
980638           920243  ...  ruben31@adventure-works.com
980639           467482  ...   akuhnertfc@themeforest.net
980640           853643  ...    anne5@adventure-works.com
980641           903958  ...     ekorneevmm@instagram.com

[980642 rows x 13 columns]

<class 'pandas.core.frame.DataFrame'>
Int64Index: 980642 entries, 0 to 980641
Data columns (total 13 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Numero da Venda       980642 non-null  int64
 1   Data da Venda         980642 non-null  object
 2   Data do Envio         980642 non-null  object
 3   ID Canal              980642 non-null  int64
 4   ID Loja               980642 non-null  int64
 5   ID Produto            980642 non-null  int64
 6   ID Promocao           980642 non-null  int64
 7   ID Cliente            980642 non-null  int64
 8   Quantidade Vendida    980642 non-null  int64
 9   Quantidade Devolvida  980642 non-null  int64
 10  Nome do Produto       980642 non-null  object
 11  Nome da Loja          980642 non-null  object
 12  E-mail do Cliente     980642 non-null  object
dtypes: int64(8), object(5)
memory usage: 104.7+ MB

### Agora, e se quisermos acrescentar uma coluna com o mês, o dia e o ano de cada venda (e não só a data completa)

In [ ]:
vendas_df['Data da Venda'] = pd.to_datetime(vendas_df['Data da Venda'], format='%d/%m/%Y')
vendas_df['Dia da Venda'] = vendas_df['Data da Venda'].dt.day
vendas_df['Mês da Venda'] = vendas_df['Data da Venda'].dt.month
vendas_df['Ano da Venda'] = vendas_df['Data da Venda'].dt.year

display(vendas_df)

        Numero da Venda Data da Venda  ... Mês da Venda  Ano da Venda
0                     1    2017-01-01  ...            1          2017
1                880458    2017-11-23  ...           11          2017
2                191019    2017-03-20  ...            3          2017
3                 18610    2017-01-08  ...            1          2017
4                287704    2017-04-23  ...            4          2017
...                 ...           ...  ...          ...           ...
980637           878244    2017-11-23  ...           11          2017
980638           920243    2017-12-09  ...           12          2017
980639           467482    2017-06-21  ...            6          2017
980640           853643    2017-11-13  ...           11          2017
980641           903958    2017-12-02  ...           12          2017

[980642 rows x 16 columns]

### E agora, caso a gente queira modificar 1 valor específico, como fazemos? Vamos importar novamente a base de produtos

In [ ]:
novo_produtos_df = pd.read_csv(r'/content/drive/ My Drive/Analise de dados/Contoso - Cadastro Produtos.csv', sep=';')
display(novo_produtos_df.head())
#repare no .head() para pegar apenas os primeiros valores, é bem comum esse uso para ter uma visão do que são os dados

                                   Nome do Produto  ... ID Subcategoria
0            Contoso Wireless Laser Mouse E50 Grey  ...              22
1    Contoso Optical Wheel OEM PS/2 Mouse E60 Grey  ...              22
2   Contoso Optical Wheel OEM PS/2 Mouse E60 Black  ...              22
3   Contoso Optical Wheel OEM PS/2 Mouse E60 White  ...              22
4  Contoso Optical Wheel OEM PS/2 Mouse E60 Silver  ...              22

[5 rows x 9 columns]

### Antes de entrar no próximo exemplo, precisamos falar de 2 métodos:
    1. loc - permite pegar uma linha de acordo com o índice dela. Ele dá erro caso não encontre o índice. Isso é interessante principalmente quando o índice é uma informação relevante ao invés só do número do índice ou quando queremos pegar alguma linha específica do dataframe (ao invés de ir do início do dataframe até a linha 5, por exemplo).
        Também podemos usar como loc[índice_linha, índice_coluna] para acessar um valor específico e modificá-lo.
    2. iloc - enxerga o dataframe como linhas e colunas e consegue pegar o valor com um número de linha e um número de coluna. Repara que ele não analisa o valor do índice da linha e da coluna, apenas a posição importa.
        Uso: iloc[num_linha, num_coluna]
        
- Vendo na prática

In [ ]:
novo_produtos_df = novo_produtos_df.set_index('Nome do Produto')
display(novo_produtos_df.head())

                                                                              Descricao do Produto  ... ID Subcategoria
Nome do Produto                                                                                     ...
Contoso Wireless Laser Mouse E50 Grey            Advanced 2.4 GHz cordless technology makes fre...  ...              22
Contoso Optical Wheel OEM PS/2 Mouse E60 Grey                       PS/2 mouse, 6 feet mouse cable  ...              22
Contoso Optical Wheel OEM PS/2 Mouse E60 Black                      PS/2 mouse, 6 feet mouse cable  ...              22
Contoso Optical Wheel OEM PS/2 Mouse E60 White                      PS/2 mouse, 6 feet mouse cable  ...              22
Contoso Optical Wheel OEM PS/2 Mouse E60 Silver                     PS/2 mouse, 6 feet mouse cable  ...              22

[5 rows x 8 columns]

In [ ]:
#vamos pegar o preço produto Contoso Optical Wheel OEM PS/2 Mouse E60 Black
#por loc
print(novo_produtos_df.loc['Contoso Optical Wheel OEM PS/2 Mouse E60 Black', 'Preco Unitario'])
#por iloc
print(novo_produtos_df.iloc[2, 5])

13
13

### A empresa decidiu aumentar o preço do produto ID 873 (Contoso Wireless Laser Mouse E50 Grey) para 23 reais. Como fazemos, para modificar isso na nossa base?

In [ ]:
#1° - novo_produtos_df.loc['Contoso Wireless Laser Mouse E50 Grey', 'Preco Unitario'] = 23
#2° - novo_produtos_df.loc[novo_produtos_df['ID Produto'] == 873, 'Preco Unitario'] = 23
display(novo_produtos_df.head())

                                                                              Descricao do Produto  ... ID Subcategoria
Nome do Produto                                                                                     ...
Contoso Wireless Laser Mouse E50 Grey            Advanced 2.4 GHz cordless technology makes fre...  ...              22
Contoso Optical Wheel OEM PS/2 Mouse E60 Grey                       PS/2 mouse, 6 feet mouse cable  ...              22
Contoso Optical Wheel OEM PS/2 Mouse E60 Black                      PS/2 mouse, 6 feet mouse cable  ...              22
Contoso Optical Wheel OEM PS/2 Mouse E60 White                      PS/2 mouse, 6 feet mouse cable  ...              22
Contoso Optical Wheel OEM PS/2 Mouse E60 Silver                     PS/2 mouse, 6 feet mouse cable  ...              22

[5 rows x 8 columns]