<a href="https://colab.research.google.com/github/GuilhermeFMedici/Exercicios_em_Python/blob/main/Filtrando_um_DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Filtrando informações nos dataframes


## Resumo

Um dos grandes potenciais do pandas é para tratar condições.

E a forma com que analisamos condições no dataframe é diferente do que já fizemos até agora no curso, vamos ver como funciona.

- Preparando as bases de dados

In [ ]:
from google.colab import drive 
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
#importando os arquivos
vendas_df = pd.read_csv(r'/content/drive/ My Drive/Analise de dados/Contoso - Vendas  - 2017.csv', sep=';')
produtos_df = pd.read_csv(r'/content/drive/ My Drive/Analise de dados/Contoso - Cadastro Produtos.csv', sep=';')
lojas_df = pd.read_csv(r'/content/drive/ My Drive/Analise de dados/Contoso - Lojas.csv', sep=';')
clientes_df = pd.read_csv(r'/content/drive/ My Drive/Analise de dados/Contoso - Clientes.csv', sep=';')

#Pegando apenas as colunas que queremos
clientes_df = clientes_df[['ID Cliente', 'E-mail']]
produtos_df = produtos_df[['ID Produto', 'Nome do Produto']]
lojas_df = lojas_df[['ID Loja', 'Nome da Loja']]

#mesclando e renomeando os dataframes
vendas_df = vendas_df.merge(produtos_df, on='ID Produto')
vendas_df = vendas_df.merge(lojas_df, on='ID Loja')
vendas_df = vendas_df.merge(clientes_df, on='ID Cliente').rename(columns={'E-mail': 'E-mail do Cliente'})
display(vendas_df)

        Numero da Venda  ...            E-mail do Cliente
0                     1  ...       rbrumfieldmy@ameblo.jp
1                880458  ...       rbrumfieldmy@ameblo.jp
2                191019  ...       rbrumfieldmy@ameblo.jp
3                 18610  ...       rbrumfieldmy@ameblo.jp
4                287704  ...       rbrumfieldmy@ameblo.jp
...                 ...  ...                          ...
980637           878244  ...           edowner9m@imdb.com
980638           920243  ...  ruben31@adventure-works.com
980639           467482  ...   akuhnertfc@themeforest.net
980640           853643  ...    anne5@adventure-works.com
980641           903958  ...     ekorneevmm@instagram.com

[980642 rows x 13 columns]

### Primeiro, vamos aplicar uma função normalmente. Qual o % das vendas que foi devolvido?

- Para isso vamos somar as quantidades nas colunas correspondentes. Lembrando, o % vai ser: Total Devolvido / Total Vendido.

In [ ]:
qtde_vendida = vendas_df['Quantidade Vendida'].sum()
qtde_devolvida = vendas_df['Quantidade Devolvida'].sum()

print('{:.2%}' .format(qtde_devolvida / qtde_vendida))

1.17%

### Agora, se quisermos fazer a mesma análise apenas para 1 loja. Queremos filtrar apenas os itens da Loja Contoso Europe Online e saber o % de devolução dessa loja.

- Para isso, vamos precisar filtrar. A forma de filtrar nos dataframes é uma "simples" comparação

In [ ]:
vendas_lojacontosoeuropeonline = vendas_df[vendas_df['ID Loja'] == 306]
display(vendas_lojacontosoeuropeonline)
qtde_vendida = vendas_lojacontosoeuropeonline['Quantidade Vendida'].sum()
qtde_devolvida = vendas_lojacontosoeuropeonline['Quantidade Devolvida'].sum()

print('{:.2%}' .format(qtde_devolvida / qtde_vendida))

        Numero da Venda  ...               E-mail do Cliente
1                880458  ...          rbrumfieldmy@ameblo.jp
17               614980  ...    makayla3@adventure-works.com
18               786402  ...    makayla3@adventure-works.com
19               383897  ...    makayla3@adventure-works.com
77               559478  ...      noah55@adventure-works.com
...                 ...  ...                             ...
885329           865745  ...        mplaskitt78@marriott.com
885356           907944  ...           eribchesteres@pbs.org
885386           919123  ...   jessica47@adventure-works.com
885390           964452  ...  terrence23@adventure-works.com
885415           900861  ...           cmordangl@webnode.com

[42771 rows x 13 columns]

1.33%

### Vamos fazer em 2 passos para entender certinho o que está acontecendo.

In [ ]:
#vendas_lojacontosoeuropeonline = vendas_df[vendas_df['ID Loja'] == 306]
#display(vendas_lojacontosoeuropeonline)

loja_306 = vendas_df['ID Loja'] == 306
vendas_lojacontosoeuropeonline = vendas_df[loja_306]
display(vendas_lojacontosoeuropeonline)

        Numero da Venda  ...               E-mail do Cliente
1                880458  ...          rbrumfieldmy@ameblo.jp
17               614980  ...    makayla3@adventure-works.com
18               786402  ...    makayla3@adventure-works.com
19               383897  ...    makayla3@adventure-works.com
77               559478  ...      noah55@adventure-works.com
...                 ...  ...                             ...
885329           865745  ...        mplaskitt78@marriott.com
885356           907944  ...           eribchesteres@pbs.org
885386           919123  ...   jessica47@adventure-works.com
885390           964452  ...  terrence23@adventure-works.com
885415           900861  ...           cmordangl@webnode.com

[42771 rows x 13 columns]

### Desafio: e se eu quisesse criar uma tabela apenas com as vendas da Loja Contoso Europe Online e que não tiveram nenhuma devolução. Quero criar essa tabela e saber quantas vendas são.

- Repare que nesse caso são 2 condições, como fazemos isso?

In [ ]:
#tudo junto
vendas_lojacontosoeuropeonline2 = vendas_df[(vendas_df['ID Loja'] == 306) & (vendas_df['Quantidade Devolvida'] == 0)]
display(vendas_lojacontosoeuropeonline)

#separado
id_loja = vendas_df['ID Loja'] == 306
qtde_devolv = vendas_df['Quantidade Devolvida'] == 0
vendas_lojacontosoeuropeonline3 = vendas_df[id_loja & qtde_devolvida]
display(vendas_lojacontosoeuropeonline3)

        Numero da Venda  ...               E-mail do Cliente
1                880458  ...          rbrumfieldmy@ameblo.jp
17               614980  ...    makayla3@adventure-works.com
18               786402  ...    makayla3@adventure-works.com
19               383897  ...    makayla3@adventure-works.com
77               559478  ...      noah55@adventure-works.com
...                 ...  ...                             ...
885329           865745  ...        mplaskitt78@marriott.com
885356           907944  ...           eribchesteres@pbs.org
885386           919123  ...   jessica47@adventure-works.com
885390           964452  ...  terrence23@adventure-works.com
885415           900861  ...           cmordangl@webnode.com

[42771 rows x 13 columns]

Empty DataFrame
Columns: [Numero da Venda, Data da Venda, Data do Envio, ID Canal, ID Loja, ID Produto, ID Promocao, ID Cliente, Quantidade Vendida, Quantidade Devolvida, Nome do Produto, Nome da Loja, E-mail do Cliente]
Index: []